import type { Metadata } from 'next';
import { Inconsolata, Inter, Lora } from 'next/font/google';

// Styles
import './globals.css';

// Fonts
const inconsolata = Inconsolata({
    subsets: ['latin']
});

const inter = Inter({ subsets: ["latin"] });

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon-32x32.png',
    },
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={ `${inconsolata.className} ${inter.className} ${lora.className} bg-white dark:bg-black-100` }>{ children }</body>
        </html>
    );
}
